/*
 * AboutDlg.java
 *
 * Created on __DATE__, __TIME__
 */

package dhost.ui;

/**
 *
 * @author  __USER__
 */
public class AboutDlg extends javax.swing.JDialog {

	/** Creates new form AboutDlg */
	public AboutDlg(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setTitle("About DHost");
		setName("abtDlg");
		getContentPane().setLayout(new java.awt.GridLayout(2, 1));

		jLabel2.setText("<html><h2>Member:</h2></html>");
		getContentPane().add(jLabel2);

		jLabel3
				.setText("<html><p>Chris</p><p></p><p>Yang</p><p></p><p>Sean</p></html>");
		getContentPane().add(jLabel3);

		jLabel1.setText("Version: v 0.1 Build: %svn% Date: %date%");
		getContentPane().add(jLabel1);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				AboutDlg dialog = new AboutDlg(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables

}