/*
 * Canvas.java
 *
 * Created on __DATE__, __TIME__
 */

package dhost.ui;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Enumeration;
import java.util.Vector;

/**
 *
 * @author  __USER__
 */
public class Canvas extends javax.swing.JPanel {

	//my code
	// Keep track of all ball center positions
	private Vector<GraphicState> gitems;

	// This is the method that is responsible for displaying the contents of the
	// canvas
	public void paintComponent(Graphics graphics) {
		// Draw the component as before (i.e., default look)
		super.paintComponent(graphics);

		// Now add all of our balls
		Enumeration<GraphicState> enumeration = gitems.elements();
		while (enumeration.hasMoreElements()) {
			GraphicState gitem = enumeration.nextElement();
			graphics.setColor(gitem.getColor());
			switch(gitem.getType())
			{
			case OVAL:
				graphics.drawOval(gitem.getPos().x, gitem.getPos().y,
						gitem.getSize().x, gitem.getSize().y);
				break;
			case RECT:
				graphics.drawRect(gitem.getPos().x, gitem.getPos().y,
						gitem.getSize().x, gitem.getSize().y);
				break;
			default:
				assert(false);
			}
		}
	}
	//end of my code
	
	/** Creates new form Canvas */
	public Canvas() {
		initComponents();
		gitems = new Vector<GraphicState>();
		setBackground(Color.white);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));
	}// </editor-fold>
	//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}